name: food_recipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  either_dart: ^1.0.0
  get_it: ^8.0.3

  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  http: ^1.2.2
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.3
  url_launcher: ^6.3.1
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - asset/image/Picture.png
  - asset/image/a1.jpg
  - asset/image/breakfast.jpg
  - asset/image/lunch.jpg
  - asset/image/dinner.png
  - asset/image/chocolate.png
  - asset/image/fish.jpg
  - asset/image/drink.jpg
  - asset/image/supper.jpg
  - asset/image/fast food.jpg
  - asset/image/sweet.jpg
  - asset/image/vegetables.jpg
  - asset/image/ee.jpg


