// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7-XWHf1HwUrQ9CHh6sd3OzHJ5Qk82am0',
    appId: '1:273913063466:web:5fa35b3d0eb6b123af7b53',
    messagingSenderId: '273913063466',
    projectId: 'todo-list-a2d2e',
    authDomain: 'todo-list-a2d2e.firebaseapp.com',
    databaseURL: 'https://todo-list-a2d2e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-a2d2e.firebasestorage.app',
    measurementId: 'G-JPTR3HEYD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA8u0fKkP6ZXRCrwZGXB_QeG31h5K1yXw',
    appId: '1:273913063466:android:21edc62c604d67b1af7b53',
    messagingSenderId: '273913063466',
    projectId: 'todo-list-a2d2e',
    databaseURL: 'https://todo-list-a2d2e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-a2d2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopktlbL9Bv1jwAkerodGmxxi2LP8CrGo',
    appId: '1:273913063466:ios:13241d0277b68928af7b53',
    messagingSenderId: '273913063466',
    projectId: 'todo-list-a2d2e',
    databaseURL: 'https://todo-list-a2d2e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-a2d2e.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAopktlbL9Bv1jwAkerodGmxxi2LP8CrGo',
    appId: '1:273913063466:ios:13241d0277b68928af7b53',
    messagingSenderId: '273913063466',
    projectId: 'todo-list-a2d2e',
    databaseURL: 'https://todo-list-a2d2e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-a2d2e.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7-XWHf1HwUrQ9CHh6sd3OzHJ5Qk82am0',
    appId: '1:273913063466:web:28bd8649e23a1df6af7b53',
    messagingSenderId: '273913063466',
    projectId: 'todo-list-a2d2e',
    authDomain: 'todo-list-a2d2e.firebaseapp.com',
    databaseURL: 'https://todo-list-a2d2e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-a2d2e.firebasestorage.app',
    measurementId: 'G-6H5JNL7RP4',
  );
}
